[package]
name = "yarr"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
lazy_static = "1.4.0"
shellexpand = "3.1.0"
help = { path = "./help" }
qqml_parser = { path = "./qqml_parser" }
