[package]
name = "qqml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtermutils = { path = "./rtermutils/" }
# no dependencies for me
