[package]
name = "qqml"
version = "0.1.0"
edition = "2021"


[lib]
name = "libqqml"
path = "./src/lib.rs"

[[bin]]
name = "qqml"
path = "./src/main.rs"

[dependencies]
rtermutils = { path = "./rtermutils/" }
# no dependencies for me
