[package]
name = "qqml"
version = "0.5.2"
edition = "2021"

[lib]
name = "libqqml"
path = "./lib/lib.rs"


[[bin]]
name = "qqml"
path = "./cli/main.rs"


[build-dependencies]
cmake = "0.1.50"
# no dependencies for me
