[package]
name = "qqml_eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qqml_parser = { path = "../qqml_parser" }
termsize = "0.1.6"
