name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Vet Go Code
      run: cd ./qpm/ && go vet ./src/main.go

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Format Go Code
      run: cd ./qpm/ && test -z $(gofmt -l .)
